# Generated by Django 5.2.4 on 2025-07-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Име')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('bio', models.TextField(verbose_name='Био')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/', verbose_name='Профилна снимка')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Имейл')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефонен номер')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='subjects.subject', verbose_name='Преподавани предмети')),
            ],
            options={
                'verbose_name': 'Учител',
                'verbose_name_plural': 'Учители',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
