# Generated by Django 5.2.4 on 2025-07-18 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заглавие на курса')),
                ('description', models.TextField(verbose_name='Описание на курса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('start_date', models.DateField(verbose_name='Начална дата')),
                ('end_date', models.DateField(verbose_name='Крайна дата')),
                ('max_students', models.PositiveIntegerField(default=10, verbose_name='Макс. брой студенти')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='subjects.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to='teachers.teacher', verbose_name='Преподавател')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсове',
                'ordering': ['start_date', 'title'],
            },
        ),
    ]
